/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Conexion.Conectar;
import java.awt.Component;
import java.awt.Graphics;
import java.awt.Image;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexm
 */
public class TablaReg extends javax.swing.JFrame {

    /**
     * Creates new form TablaReg
     */
    
    private final String SQL_SELECT= "Select * from usuario";

   
    
     String saludo="";
       
    public TablaReg() {
       
        Login b = new Login();
       this.saludo="Bienvenido "+b.guardar;
       
        initComponents();
        consultar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Usertext = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        Telnumtext = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        NameFulltext = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        COELtext = new javax.swing.JTextField();
        Label_conta2 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        CerrarSeccionbotton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Bienvenido = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Agregarbotton = new javax.swing.JButton();
        SalirBotton4 = new javax.swing.JButton();
        SalirBotton5 = new javax.swing.JButton();
        SalirBotton6 = new javax.swing.JButton();
        Contratext = new javax.swing.JPasswordField();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de nuevo usuario.");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setForeground(new java.awt.Color(51, 51, 51));

        Usertext.setBackground(new java.awt.Color(51, 51, 51));
        Usertext.setForeground(new java.awt.Color(255, 255, 255));
        Usertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsertextActionPerformed(evt);
            }
        });

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Nombre completo");

        Telnumtext.setBackground(new java.awt.Color(51, 51, 51));
        Telnumtext.setForeground(new java.awt.Color(255, 255, 255));
        Telnumtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelnumtextActionPerformed(evt);
            }
        });

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Numero de Telefono");

        NameFulltext.setBackground(new java.awt.Color(51, 51, 51));
        NameFulltext.setForeground(new java.awt.Color(255, 255, 255));
        NameFulltext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFulltextActionPerformed(evt);
            }
        });

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText(" Correo Electronico");

        COELtext.setBackground(new java.awt.Color(51, 51, 51));
        COELtext.setForeground(new java.awt.Color(255, 255, 255));
        COELtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COELtextActionPerformed(evt);
            }
        });

        Label_conta2.setBackground(new java.awt.Color(255, 255, 255));
        Label_conta2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        Label_conta2.setForeground(new java.awt.Color(255, 255, 255));
        Label_conta2.setText("Contraseña");

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Nombre de usuario");

        CerrarSeccionbotton.setBackground(new java.awt.Color(255, 102, 102));
        CerrarSeccionbotton.setForeground(new java.awt.Color(255, 255, 255));
        CerrarSeccionbotton.setText("Cerrar sección.");
        CerrarSeccionbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSeccionbottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usertext, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameFulltext, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(COELtext, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(6, 6, 6)
                                .addComponent(Telnumtext, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addComponent(Label_conta2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(9, 9, 9))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CerrarSeccionbotton)))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usertext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(NameFulltext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(COELtext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Telnumtext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(Label_conta2)
                .addGap(49, 49, 49)
                .addComponent(CerrarSeccionbotton)
                .addContainerGap())
        );

        Tabla.setBackground(new java.awt.Color(0, 255, 255));
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario", "Nombre", "Telefono", "Correo", "Contrasena"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Bienvenido.setBackground(new java.awt.Color(255, 255, 255));
        Bienvenido.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        Bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        Bienvenido.setText(saludo);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestión de usuarios");

        Agregarbotton.setBackground(new java.awt.Color(255, 102, 0));
        Agregarbotton.setForeground(new java.awt.Color(255, 255, 255));
        Agregarbotton.setText("Agregar");
        Agregarbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarbottonActionPerformed(evt);
            }
        });

        SalirBotton4.setBackground(new java.awt.Color(204, 0, 0));
        SalirBotton4.setForeground(new java.awt.Color(255, 255, 255));
        SalirBotton4.setText("Eliminar");
        SalirBotton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBotton4ActionPerformed(evt);
            }
        });

        SalirBotton5.setBackground(new java.awt.Color(0, 153, 255));
        SalirBotton5.setForeground(new java.awt.Color(255, 255, 255));
        SalirBotton5.setText("Modificar");
        SalirBotton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBotton5ActionPerformed(evt);
            }
        });

        SalirBotton6.setBackground(new java.awt.Color(102, 204, 0));
        SalirBotton6.setForeground(new java.awt.Color(255, 255, 255));
        SalirBotton6.setText("Buscar");
        SalirBotton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirBotton6ActionPerformed(evt);
            }
        });

        Contratext.setBackground(new java.awt.Color(51, 51, 51));
        Contratext.setForeground(new java.awt.Color(255, 255, 255));
        Contratext.setText("s");
        Contratext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContratextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(Bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(113, 113, 113)
                        .addComponent(Contratext, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(220, 220, 220)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(Agregarbotton, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SalirBotton4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SalirBotton5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(SalirBotton6))
                    .addComponent(jLabel3)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(503, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Bienvenido)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Contratext, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregarbotton, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(SalirBotton4, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(SalirBotton5, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(SalirBotton6, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE))
                .addGap(16, 16, 16))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(76, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void COELtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COELtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COELtextActionPerformed

    private void NameFulltextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFulltextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFulltextActionPerformed

    private void TelnumtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelnumtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelnumtextActionPerformed

    private void UsertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsertextActionPerformed

    private void CerrarSeccionbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSeccionbottonActionPerformed
      
        Login a = new Login();
        this.setVisible(false);
        a.setVisible(true);
        
    }//GEN-LAST:event_CerrarSeccionbottonActionPerformed

    private void AgregarbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarbottonActionPerformed
        
        
        agregar();
        consultar();
        
        
    }//GEN-LAST:event_AgregarbottonActionPerformed

    private void SalirBotton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirBotton4ActionPerformed

    private void SalirBotton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirBotton5ActionPerformed

    private void SalirBotton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirBotton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SalirBotton6ActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked

        if(evt.getClickCount()==1){

            JTable recibir = (JTable) evt.getSource();

            Usertext.setText(recibir.getModel().getValueAt(recibir.getSelectedRow(), 1).toString());
            NameFulltext.setText(recibir.getModel().getValueAt(recibir.getSelectedRow(), 2).toString());
            Telnumtext.setText(recibir.getModel().getValueAt(recibir.getSelectedRow(), 3).toString());
            COELtext.setText(recibir.getModel().getValueAt(recibir.getSelectedRow(), 4).toString());
            Contratext.setText(recibir.getModel().getValueAt(recibir.getSelectedRow(), 5).toString());

        }

    }//GEN-LAST:event_TablaMouseClicked

    private void ContratextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContratextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContratextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaReg().setVisible(true);
            }
        });
    }
    
    
    void consultar(){
        String sql = "Select * from usuario";
        Conectar a = new Conectar();


        try {
            
           
            Connection conet = a.getConnection();
          
            Statement  st = conet.createStatement();
          var  rs = st.executeQuery(sql);
            
            var usuario = new Object[6];
           var model = (DefaultTableModel) Tabla.getModel();
            while (rs.next()){
                usuario [0] = rs.getInt("id");
                usuario [1] = rs.getString("nombre_usuario");
                usuario [2] = rs.getString("nombre_completo");
                usuario [3] = rs.getString("telefono");
                usuario [4] = rs.getString("correo");
                usuario [5] = rs.getString("contrasena");
                
                model.addRow(usuario);
            }
            Tabla.setModel(model);
            
        } catch (SQLException e){
            System.out.println("Ocurrio un problema con la tabla: "+e);
        }    
    }
    
    public void agregar(){
         
        String user = this.Usertext.getText();
        String Nom = this.NameFulltext.getText();
      
        String tell = this.Telnumtext.getText();
        String Correo = this.COELtext.getText();
        String pass1 = new String(this.Contratext.getPassword());
        
        if(user.equals("")|| Nom.equals("") || tell.equals("")|| Correo.equals("") || pass1.equals("")){
        
            JOptionPane.showMessageDialog((Component)null,"Necesita llenar todas las casillas para completar el registro");
            
        }else{
         
          
            
                try{
                Conectar conex = new Conectar();
               
      PreparedStatement PS = conex.getConnection().prepareStatement("INSERT INTO usuario(nombre_usuario,nombre_completo,telefono,correo,contrasena) VALUES (?,?,?,?,?)");
      PS.setString(1, user);
      PS.setString(2, Nom);
      PS.setString(3, tell);
      PS.setString(4, Correo); 
      PS.setString(5, pass1);
   
       JOptionPane.showMessageDialog((Component)null,"Regstro exitoso del usuario: "+user);
            
      PS.executeUpdate();
     
                }catch(SQLException e){
                    
                    
                 JOptionPane.showMessageDialog((Component)null,"Error, el nombre de usuario ingresado ya existe, pruebe otro.  o sino es otro error: "+e);
            
                   
                }
          
          
        }
    
        
    
    }
    public void modificar(){
   //  String Usuario = userName.getText();
     //   String Nombre = name.getText();
       // String Telefono = telephone.getText();
        //String Correo = email.getText();
        //String Contrasena = new String(Password.getPassword());
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregarbotton;
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JTextField COELtext;
    private javax.swing.JButton CerrarSeccionbotton;
    private javax.swing.JPasswordField Contratext;
    private javax.swing.JLabel Label_conta2;
    private javax.swing.JTextField NameFulltext;
    private javax.swing.JButton SalirBotton4;
    private javax.swing.JButton SalirBotton5;
    private javax.swing.JButton SalirBotton6;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField Telnumtext;
    private javax.swing.JTextField Usertext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
