/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Forms;

import Conexion.Conectar;
import java.awt.Component;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author alexm
 */
public class TablaReg extends javax.swing.JFrame {

    /**
     * Creates new form TablaReg
     */
     
    //Crea una variable con el modelo de la tabla
    DefaultTableModel model;
    
  //Esta variable cambiara dependiendo del usuario que inicie seccion para darle la bienvenida
     String saludo="";
       
    public TablaReg() {
       
      Login b = new Login();
     
    this.saludo="Bienvenido "+b.getGuardar();
               //Se inician los componentes
        initComponents();
        //Se llama al metodo que muestra la tabla con los datos
        mostrar();  
        
        
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        Usertext = new javax.swing.JTextField();
        jLabel31 = new javax.swing.JLabel();
        Telnumtext = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        NameFulltext = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        COELtext = new javax.swing.JTextField();
        Label_conta2 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        CerrarSeccionbotton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        Bienvenido = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Agregarbotton = new javax.swing.JButton();
        Eliminarbotton = new javax.swing.JButton();
        Modificarbotton = new javax.swing.JButton();
        Contratext = new javax.swing.JPasswordField();
        Limpiar = new javax.swing.JButton();

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Registro de nuevo usuario.");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(0, 51, 102));

        jPanel4.setBackground(new java.awt.Color(51, 51, 51));
        jPanel4.setForeground(new java.awt.Color(51, 51, 51));

        Usertext.setBackground(new java.awt.Color(51, 51, 51));
        Usertext.setForeground(new java.awt.Color(255, 255, 255));
        Usertext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsertextActionPerformed(evt);
            }
        });

        jLabel31.setBackground(new java.awt.Color(255, 255, 255));
        jLabel31.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Nombre completo");

        Telnumtext.setBackground(new java.awt.Color(51, 51, 51));
        Telnumtext.setForeground(new java.awt.Color(255, 255, 255));
        Telnumtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelnumtextActionPerformed(evt);
            }
        });

        jLabel32.setBackground(new java.awt.Color(255, 255, 255));
        jLabel32.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Numero de Telefono");

        NameFulltext.setBackground(new java.awt.Color(51, 51, 51));
        NameFulltext.setForeground(new java.awt.Color(255, 255, 255));
        NameFulltext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameFulltextActionPerformed(evt);
            }
        });

        jLabel33.setBackground(new java.awt.Color(255, 255, 255));
        jLabel33.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText(" Correo Electronico");

        COELtext.setBackground(new java.awt.Color(51, 51, 51));
        COELtext.setForeground(new java.awt.Color(255, 255, 255));
        COELtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                COELtextActionPerformed(evt);
            }
        });

        Label_conta2.setBackground(new java.awt.Color(255, 255, 255));
        Label_conta2.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        Label_conta2.setForeground(new java.awt.Color(255, 255, 255));
        Label_conta2.setText("Contraseña");

        jLabel35.setBackground(new java.awt.Color(255, 255, 255));
        jLabel35.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Nombre de usuario");

        CerrarSeccionbotton.setBackground(new java.awt.Color(255, 102, 102));
        CerrarSeccionbotton.setForeground(new java.awt.Color(255, 255, 255));
        CerrarSeccionbotton.setText("Cerrar sección.");
        CerrarSeccionbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CerrarSeccionbottonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel35, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Usertext, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NameFulltext, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(COELtext, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(62, 62, 62))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(CerrarSeccionbotton))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Label_conta2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(Telnumtext, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(jLabel35)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Usertext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addGap(18, 18, 18)
                .addComponent(NameFulltext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(COELtext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Telnumtext, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_conta2)
                .addGap(55, 55, 55)
                .addComponent(CerrarSeccionbotton)
                .addContainerGap())
        );

        Tabla.setBackground(new java.awt.Color(0, 255, 255));
        Tabla.setFont(new java.awt.Font("Verdana", 0, 10)); // NOI18N
        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Usuario", "Nombre", "Telefono", "Correo", "Contrasena"
            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(Tabla);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 6, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 661, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        Bienvenido.setBackground(new java.awt.Color(255, 255, 255));
        Bienvenido.setFont(new java.awt.Font("Georgia", 0, 18)); // NOI18N
        Bienvenido.setForeground(new java.awt.Color(255, 255, 255));
        Bienvenido.setText(saludo);

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Georgia", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Gestión de usuarios");

        Agregarbotton.setBackground(new java.awt.Color(255, 102, 0));
        Agregarbotton.setForeground(new java.awt.Color(255, 255, 255));
        Agregarbotton.setText("Agregar");
        Agregarbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgregarbottonActionPerformed(evt);
            }
        });

        Eliminarbotton.setBackground(new java.awt.Color(204, 0, 0));
        Eliminarbotton.setForeground(new java.awt.Color(255, 255, 255));
        Eliminarbotton.setText("Eliminar");
        Eliminarbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminarbottonActionPerformed(evt);
            }
        });

        Modificarbotton.setBackground(new java.awt.Color(0, 153, 255));
        Modificarbotton.setForeground(new java.awt.Color(255, 255, 255));
        Modificarbotton.setText("Modificar");
        Modificarbotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarbottonActionPerformed(evt);
            }
        });

        Contratext.setBackground(new java.awt.Color(51, 51, 51));
        Contratext.setForeground(new java.awt.Color(255, 255, 255));
        Contratext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContratextActionPerformed(evt);
            }
        });

        Limpiar.setBackground(new java.awt.Color(0, 204, 51));
        Limpiar.setForeground(new java.awt.Color(255, 255, 255));
        Limpiar.setText("Limpiar");
        Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addComponent(Bienvenido, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(119, 119, 119)
                                .addComponent(Contratext, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(186, 186, 186)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(493, 493, 493)
                        .addComponent(Agregarbotton, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Eliminarbotton, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Modificarbotton, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(8, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel2Layout.createSequentialGroup()
                    .addGap(47, 47, 47)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(503, Short.MAX_VALUE)))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Bienvenido)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Contratext, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Agregarbotton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Eliminarbotton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Modificarbotton, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                    .addContainerGap(76, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(16, 16, 16)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void COELtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_COELtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_COELtextActionPerformed

    private void NameFulltextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameFulltextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameFulltextActionPerformed

    private void TelnumtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelnumtextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelnumtextActionPerformed

    private void UsertextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsertextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UsertextActionPerformed

    private void CerrarSeccionbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CerrarSeccionbottonActionPerformed
      
        Login a = new Login();
        this.setVisible(false);
        a.setVisible(true);
        
    }//GEN-LAST:event_CerrarSeccionbottonActionPerformed

    private void AgregarbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarbottonActionPerformed
        
        //Metodo para agregar el usuario
        agregar();
        //Metodo para limpiar la tabla
           Cls_Tabla();
           //Metodo para volver a mostrar la tabla con los datos actualizados
            mostrar();
      
        
        
    }//GEN-LAST:event_AgregarbottonActionPerformed

    
    private void EliminarbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminarbottonActionPerformed
     
        //Metodo para eliminar el usuario
       Eliminar();
 //Metodo para limpiar la tabla
     Cls_Tabla();
        //Metodo para volver a mostrar la tabla con los datos actualizados
     mostrar();
        
    }//GEN-LAST:event_EliminarbottonActionPerformed

      void Cls_Tabla(){
      
          //Limpia la tabla
          model.getDataVector().removeAllElements();
          
          //Actualiza la tabla
      Tabla.updateUI();;
    }
   
    
    private void ModificarbottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarbottonActionPerformed
     
        modificar();
        Cls_Tabla();
        mostrar();
    }//GEN-LAST:event_ModificarbottonActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
    
        if(evt.getClickCount()==1){

            JTable recibir = (JTable) evt.getSource();

            Usertext.setText(recibir.getModel().getValueAt(recibir.getSelectedRow(), 1).toString());
            NameFulltext.setText(recibir.getModel().getValueAt(recibir.getSelectedRow(), 2).toString());
            Telnumtext.setText(recibir.getModel().getValueAt(recibir.getSelectedRow(), 3).toString());
            COELtext.setText(recibir.getModel().getValueAt(recibir.getSelectedRow(), 4).toString());
            Contratext.setText(recibir.getModel().getValueAt(recibir.getSelectedRow(), 5).toString());

        }

    }//GEN-LAST:event_TablaMouseClicked

    private void ContratextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContratextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContratextActionPerformed

    private void LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LimpiarActionPerformed

        //Metodo para limpiar los datos ingresados 
        limpiar();
    }//GEN-LAST:event_LimpiarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaReg.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaReg().setVisible(true);
            }
        });
    }
    
    
   //Metodo que muestra los datos de la tabla
   private void mostrar(){
       
       //Se crea una variable que almacene la consulta
        String sql = "Select * from usuario";
        Conectar a = new Conectar();
ResultSet rs;
        try {
            
            Connection conet = a.getConnection();
          
            Statement  st = conet.createStatement();
            rs = st.executeQuery(sql);
            
            Object[] usuario = new Object[6];
            //Se van ejecutando los datos mientras y poniendolos existan en la tabla
          model = (DefaultTableModel) Tabla.getModel();
            while (rs.next()){
                usuario [0] = rs.getInt("id");
                usuario [1] = rs.getString("nombre_usuario");
                usuario [2] = rs.getString("nombre_completo");
                usuario [3] = rs.getString("telefono");
                usuario [4] = rs.getString("correo");
                usuario [5] = rs.getString("contrasena");
               
               model.addRow(usuario);
            }
            Tabla.setModel(model);
            
        } catch (SQLException e){
            System.out.println("Ocurrio un problema con la tabla: "+e);
        }    
    }
   
   
     private void Eliminar(){
     Conectar conex = new Conectar();
        Connection con=conex.getConnection();
        String user = this.Usertext.getText();
         
            String sql="select * from usuario where nombre_usuario like '"+user+"'";

        
           if(!user.equals("")){
         try{
     
             Statement st=con.createStatement();
             
                   ResultSet rs=st.executeQuery(sql);
     PreparedStatement PS = conex.getConnection().prepareStatement("Delete from usuario where nombre_usuario = ?");

      PS.setString(1, user);
      
      //En el caso de que haya un usuario que exista con el nombre ingresado se ejecuta:
      if(rs.next()){
          
          int resultado=1;
          
          if(resultado==1){
          JOptionPane.showMessageDialog((Component)null,"Registro eliminado exitosamente del usuario: "+user);
           
     PS.executeUpdate();
         
     
          }
            
      }else{
       JOptionPane.showMessageDialog((Component)null,"El usuario ingresado no existe");
       
         }
      }catch(SQLException e){
      
         JOptionPane.showMessageDialog((Component)null,"Error:"+e); 
        
      }
         
        
           }
         
         
         else{
           
             JOptionPane.showMessageDialog(null,"El nombre del usuario es obligatorio para eliminarlo. Intente de nuevo");
          
                   
           }

    
    }
    
    private void agregar(){
         
        Conectar conex = new Conectar();
        Connection con=conex.getConnection();
     
        String user = this.Usertext.getText();
        String Nom = this.NameFulltext.getText();
      
        String tell = this.Telnumtext.getText();
        String Correo = this.COELtext.getText();
        String pass1 = new String(this.Contratext.getPassword());
        
          String sql="select * from usuario where nombre_usuario like '"+user+"'";

        
        if(user.equals("")|| Nom.equals("") || tell.equals("")|| Correo.equals("") || pass1.equals("")){
        
            JOptionPane.showMessageDialog((Component)null,"Necesita llenar todas las casillas para completar el registro");
              
        }else{
            
                try{ 
              
         Statement st=con.createStatement();
             
                   ResultSet rs=st.executeQuery(sql);
        //Si no hay usuarios con el nombre ingresado se ejecuta esto:
      if(!rs.next()){
          
          int resultado=1;
          
          if(resultado==1){
     
            PreparedStatement PS = conex.getConnection().prepareStatement("INSERT INTO usuario(nombre_usuario,nombre_completo,telefono,correo,contrasena) VALUES (?,?,?,?,?)");
      PS.setString(1, user);
      PS.setString(2, Nom);
      PS.setString(3, tell);
      PS.setString(4, Correo); 
      PS.setString(5, pass1);
        
      PS.executeUpdate();
        JOptionPane.showMessageDialog((Component)null,"Regstro exitoso del usuario: "+user);  
              
          }
      }
      else{
          
        JOptionPane.showMessageDialog((Component)null,"Error, el nombre de usuario ingresado ya existe, pruebe otro.");
            
      }
      
                }catch(SQLException e){
                    
                 JOptionPane.showMessageDialog((Component)null,"Error, el nombre de usuario ingresado ya existe, pruebe otro.  o sino es otro error: "+e);
            
                   
                }
                
          
        }
   
    }
    private void modificar(){
    String user = this.Usertext.getText();
        String Nom = this.NameFulltext.getText();
        String tell = this.Telnumtext.getText();
        String Correo = this.COELtext.getText();
        String pass1 = new String(this.Contratext.getPassword());
        
           
    
        try {
            
        
  
            if (user.equals("") || Nom.equals("") || tell.equals("") || Correo.equals("") || pass1.equals("")){
                JOptionPane.showMessageDialog(null, "Hay campos vacios, es obligatorio ingresar todos para modificar");
              
            } else {
                Conectar conex=new Conectar();
                String sql = "update usuario set nombre_usuario = '"+user+"', nombre_completo = '"+Nom+"', telefono = '"+tell+"', correo = '"+Correo+"', contrasena = '"+pass1+"' where nombre_usuario = '" +user+"'";
             
          String sql2="select * from usuario where nombre_usuario like '"+user+"'";

                Connection conex1 = conex.getConnection();
                  Statement st = conex1.createStatement();
                st.executeUpdate(sql);
                    ResultSet rs=st.executeQuery(sql2);
        //Si el usuario ingresado existe entoces se puede modificar sus datos:
      if(rs.next()){
          
          int resultado=1;
      
                   if(resultado==1){
                       
                       
                                     JOptionPane.showMessageDialog(null, "EL usuario ha sido modificaddo");
                
                       
                       
                   }
      
      
      }else{
      
        JOptionPane.showMessageDialog(null, "EL nombre usuario no puede ser cambiado o no existe");
                 
      }
            }
        } catch (SQLException e) {
            
                  JOptionPane.showMessageDialog(null, "Hay campos vacios, es obligatorio ingresar todos para modificar"+e);
        }
        
         
      
    }
    
    public  void limpiar(){
     this.Usertext.setText("");
         this.Contratext.setText("");
   
         this.COELtext.setText("");
         this.Telnumtext.setText("");
         this.NameFulltext.setText("");
         
    }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agregarbotton;
    private javax.swing.JLabel Bienvenido;
    private javax.swing.JTextField COELtext;
    private javax.swing.JButton CerrarSeccionbotton;
    private javax.swing.JPasswordField Contratext;
    private javax.swing.JButton Eliminarbotton;
    private javax.swing.JLabel Label_conta2;
    private javax.swing.JButton Limpiar;
    private javax.swing.JButton Modificarbotton;
    private javax.swing.JTextField NameFulltext;
    private javax.swing.JTable Tabla;
    private javax.swing.JTextField Telnumtext;
    private javax.swing.JTextField Usertext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane4;
    // End of variables declaration//GEN-END:variables
}
